name: Bug Report
description: "Problems with RF-DETR+"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an RF-DETR+ Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the RF-DETR+ [issues](https://github.com/roboflow/rf-detr-plus/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the RF-DETR+ issues and found no similar bug report.
          required: true

  - type: textarea
    attributes:
      label: Bug
      description: >
        Please provide as much information as possible. Include full console output and error messages (including any traceback). Use Markdown to format text, code, and logs. Screenshots can help clarify visual issues.
      placeholder: |
        Include logs, tracebacks, screenshots, or any other relevant info to help us quickly diagnose and solve your problem.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide details about your setup:
        - RF-DETR+ version
        - OS (e.g. Ubuntu 20.04, Windows 10)
        - Python version
        - PyTorch version
        - CUDA/cuDNN version
        - GPU/CPU hardware
      placeholder: |
        Example:
        - RF-DETR+: 0.1.0
        - OS: Ubuntu 20.04
        - Python: 3.10.0
        - PyTorch: 2.0.0
        - GPU: NVIDIA RTX 4080
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        Provide code or steps that are as minimal and self-contained as possible to reproduce the issue.
      placeholder: |
        ```
        # Example code to reproduce your issue
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: |
        Anything else you would like to share? (Optional)

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a Pull Request to help improve RF-DETR+.
      options:
        - label: Yes, I'd like to help by submitting a PR!
