name: Feature Request
description: Suggest an idea for RF-DETR+
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an RF-DETR+ Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/roboflow/rf-detr-plus/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the RF-DETR+ [issues](https://github.com/roboflow/rf-detr-plus/issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see in RF-DETR+?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a Pull Request to help improve RF-DETR+.
      options:
        - label: Yes I'd like to help by submitting a PR!
